### ISSUE TITLE
Bundlers

### ISSUE THREAD

**Issue by toreylittlefield** [roarcoders/scrumblr-enhancement#28]
Try https://esbuild.github.io/ or https://parceljs.org/ both are very easy. It's generally much better to use a bundler anyways because (depending on your config) you'll get dead code elimination (tree shaking), avoid collisions, and you'll probably want to transpire you modern JS into something more supported anyways etc...

Hope that's helpful.

Here's a great article explaining build tools and why to use them and what the do. Helped me learn a lot about the why's and how they work: https://www.swyx.io/writing/jobs-of-js-build-tools/

Also didn't read over your codebase but you could try importing your JS scripts in your html with 

`<script type=module src=index.js />`

**Comment by zainafzal88** [comment]
Thanks @toreylittlefield . Will look into it soon.

**Comment by zainafzal88** [comment]
Will check this after the first release
