### ISSUE TITLE
Cors AWS

### ISSUE THREAD

**Issue by toreylittlefield** [roarcoders/scrumblr-enhancement#30]
If it's helpful https://aws.amazon.com/blogs/compute/configuring-cors-on-amazon-api-gateway-apis/

And I wasn't kidding The Amazon API Gateway CORS Configurator

 https://cors.serverlessland.com/

The CORS configurator helps you configure CORS on API Gateway for REST or HTTP APIs. Fill in the information above and the configurator will generate the AWS SAM configuration as well as a response example.

@zainafzal88 @404Kartik

**Comment by zainafzal88** [comment]
Thanks @toreylittlefield . That's helpful. Will give it a go

**Comment by zainafzal88** [comment]
Will come back to this probably after the 1st release. For now, closing it

**Comment by andreigec** [comment]
:kappa
