### ISSUE TITLE
[HOLD] - Create Cloudfront Distribution and point it to S3 bucket

### ISSUE THREAD

**Issue by zainafzal88** [roarcoders/scrumblr-enhancement#9]
This will be done later as it will only be beneficial when we launch beta testing (internal live testing)

**Comment by drumovski** [comment]
Looks like LocalStack only provides cloudfront in the pro version which is approx $30 /month with a 14 day free trial.
Alternatively, We could just use AWS itself. The free tier (if you are in the first 12 months includes  2,000,000 HTTP or HTTPS Requests / 2,000,000 CloudFront Function Invocations

**Comment by toreylittlefield** [comment]
@zainafzal88 This is done
